export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
}

// {
//   "login": "adilmayank",
//   "id": 94361109,
//   "node_id": "U_kgDOBZ_WFQ",
//   "avatar_url": "https://avatars.githubusercontent.com/u/94361109?v=4",
//   "gravatar_id": "",
//   "url": "https://api.github.com/users/adilmayank",
//   "html_url": "https://github.com/adilmayank",
//   "followers_url": "https://api.github.com/users/adilmayank/followers",
//   "following_url": "https://api.github.com/users/adilmayank/following{/other_user}",
//   "gists_url": "https://api.github.com/users/adilmayank/gists{/gist_id}",
//   "starred_url": "https://api.github.com/users/adilmayank/starred{/owner}{/repo}",
//   "subscriptions_url": "https://api.github.com/users/adilmayank/subscriptions",
//   "organizations_url": "https://api.github.com/users/adilmayank/orgs",
//   "repos_url": "https://api.github.com/users/adilmayank/repos",
//   "events_url": "https://api.github.com/users/adilmayank/events{/privacy}",
//   "received_events_url": "https://api.github.com/users/adilmayank/received_events",
//   "type": "User",
//   "site_admin": false,
//   "name": "Adil Mayank",
//   "company": "Cartesian Services",
//   "blog": "",
//   "location": "Zirakpur",
//   "email": null,
//   "hireable": null,
//   "bio": "Currently, a Web Developer Trainee working at Cartesian Services.  1 year and 1 month experience. Worked in  JavaScript, HTML, CSS, C#, Python, VBA so far.\r\n",
//   "twitter_username": null,
//   "public_repos": 6,
//   "public_gists": 0,
//   "followers": 0,
//   "following": 0,
//   "created_at": "2021-11-15T10:15:38Z",
//   "updated_at": "2023-02-04T11:34:15Z"
// }
